# Generated by Django 3.1.7 on 2021-05-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checksho_bot', '0001_initial'),
        ('users', '0001_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checksho_bot.telegramuser'),
        ),
    ]
