# Generated by Django 3.1.7 on 2021-03-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_campaign_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='interval',
            field=models.CharField(blank=True, choices=[('HOUR', 'HOUR'), ('DAY', 'DAY'), ('WEEK', 'WEEK')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
