# Generated by Django 3.1.7 on 2021-03-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_interval_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Description')),
                ('url', models.URLField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
