# Generated by Django 3.1.7 on 2021-03-28 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignitem',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_items', to='campaigns.campaign'),
        ),
    ]
