# Generated by Django 3.1.7 on 2021-05-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_related_name_market_title_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_email_campaign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_telegram_campaign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='next_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
