# Generated by Django 3.1.7 on 2021-05-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaignitem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignitem',
            old_name='type',
            new_name='types',
        ),
    ]
