# Generated by Django 3.1.7 on 2021-05-30 19:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaignitem_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignitem',
            name='is_notify_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignitem',
            name='is_notify_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaignitem',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['NOTIFY_SALE', 'Notify sale'], ['NOTIFY_AVAILABLE', 'Notify available']], max_length=50, null=True),
        ),
    ]
